import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios';
import { useState } from 'react';
import Link from 'next/link';
import Select from 'react-select';
import Layout from '../components/layout';

const chain_options = [
  { value: 1, label: 'Ethereum' },
  { value: 137, label: 'Matic' },
  { value: 43114, label: 'Avalanche' },
  { value: 56, label: 'BSC' },
  { value: 42161, label: 'Arbitrum' },
  { value: 250, label: 'Fantom' },
  { value: 1284, label: 'Moonbeam' },
  { value: 1285, label: 'Moonriver' },
  { value: 2020, label: 'Axie' },
  { value: 9001, label: 'Evmos' },
  { value: 592, label: 'Astar' },
  { value: 336, label: 'Shiden' },
  { value: 4689, label: 'IoTeX' },
  { value: 1666600000, label: 'Harmony' },
  { value: 25, label: 'Cronos' },
  { value: 1313161554, label: 'Aurora' },
  { value: 53935, label: 'Defi Kingdoms' },
]

export default function Home({ user }) {
    // assets, quantity, price
    const [assets, setAssets] = useState([]);
    const [address, setAddress] = useState('');
    const [chainID, setChainID] =  useState(1);
  
    const handleAddress = (e) => {
      setAddress(e.target.value);
    }

    const handleChainID = (e) => {
      setChainID(e.value);
    }
  
    async function getAssets() {
      setAssets([]);
      await axios
        .get(`https://api.covalenthq.com/v1/${chainID}/address/${address}/balances_v2/`, {
          auth: {
            username: process.env.NEXT_PUBLIC_COVALENT_API,
            password: '',
          },
        })
        .then((response) => {
          const items = response.data.data.items;
          for (let i = 0; i < items.length; i++) {
            setAssets((assets) => [
              ...assets,
              {
                name: items[i].contract_name,
                quantity: items[i].balance,
                price: items[i].quote_rate,
              },
            ]);
          }
        });
    }

  return (
    <div>
      <Head>
        <title>Portfolios</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="page-container">
            <div id="content-wrap">
                <div className="navbar bg-base-100">
                    <div className="navbar-start">
                        <div className="dropdown">
                        <label tabIndex={0} className="btn btn-ghost lg:hidden">
                            <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 6h16M4 12h8m-8 6h16" /></svg>
                        </label>
                        <ul tabIndex={0} className="menu menu-compact dropdown-content mt-3 p-2 shadow bg-base-100 rounded-box w-52">
                            <li><Link href="/">Home</Link></li>
                            <li><Link href="/oportfolio">Portfolio</Link></li>
                        </ul>
                        </div>
                        <Link href="/webapp" className="btn btn-ghost normal-case text-xl">Sunrise Portfolio & NFTs</Link>
                    </div>
                    <div className="navbar-center hidden lg:flex">
                        <ul className="menu menu-horizontal p-0">
                          <li><Link href="/">Home</Link></li>
                          <li><Link href="/oportfolio">Portfolio</Link></li>
                        </ul>
                    </div>
                    <div className="navbar-end">
                    </div>
                </div>
            <main>
              <div className='flex justify-center mt-4'>
                <Link href="/" className="link link-primary m-4">Log In by connecting Metamask to access Marketplace</Link>
              </div>
                <div className='flex justify-center mt-10'>
                    <input type="text" placeholder="Wallet Address" className="input input-bordered w-full max-w-md mx-4" onChange={handleAddress} />
                    <Select options={chain_options} className="w-full max-w-xs mx-4" onChange={handleChainID} />
                    <button className="btn" onClick={getAssets}>Get Assets</button>
                    < br/>
                </div>

                <div>
                      <div className='flex justify-center items-center'>
                        {assets.length > 0 && (
                            <table className="table w-full m-2">
                                <thead>
                                    <tr>
                                        <th className="table-cell">#</th>
                                        <th className="table-cell">Asset</th>
                                        <th className="table-cell">Quantity</th>
                                        <th className="table-cell">Price</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {assets.map((asset) => (
                                        <tr key={asset.name}>
                                            <td className="table-cell">{assets.indexOf(asset) + 1}</td>
                                            <td className="table-cell">{asset.name}</td>
                                            <td className="table-cell">{asset.quantity}</td>
                                            <td className="table-cell">{asset.price}</td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        )} 
                    </div> 
                </div>
            </main>
            </div>
            <div id="footer">
                <footer className="footer footer-center p-4 bg-base-300 text-base-content">
                    <div>
                        <p>Copyright © 2022 - All right reserved by Momo</p>
                    </div>
                </footer>
            </div>
        </div>
    </div>
  )
}
